# Generated by Django 4.2.30 on 2026-06-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_created', 'Заявка создана'), ('new_response', 'Новый отклик'), ('participation_approved', 'Участие подтверждено'), ('participation_rejected', 'Участие отклонено'), ('new_request_nearby', 'Новая заявка рядом'), ('activity_reminder', 'Напоминание об активности'), ('request_cancelled', 'Заявка отменена'), ('request_rescheduled', 'Заявка перенесена'), ('new_message', 'Новое сообщение'), ('new_review', 'Новый отзыв')], max_length=50, verbose_name='Тип уведомления'),
        ),
    ]
